index:
    path: /
    controller: App\Controller\AccueilController::accueil

index_name:
    path: /hello/{name}
    controller: App\Controller\DefaultController::index_name

#ajout_annonce:
#    path: /ajout
#    controller: App\Controller\AjoutController::ajoutAnnonce

ajout_annonce:
    path: /ajout
    controller: App\Controller\FormulaireController::new

formulaire_ajout:
    path: /ajaxCreation
    controller: App\Controller\AjoutController::formulaireAjout

security_login:
    path: /login
    controller: App\Controller\LoginController::login

app_login_check:
    path: /login_check

security_logout:
    path: /logout